INSERT INTO books (title, author_id, publication_date, genre, isbn, cover_image_url, summary, status, rating) VALUES
  ('Life Of PI', 1, '2022-10-15', 'Fiction', '9780123456789', 'https://m.media-amazon.com/images/I/71q81GUuTmL._SL1500_.jpg', 'Summary of Book 1', 'available', 4.2),
  ('IKIGAI', 2, '2021-07-20', 'Mystery', '9781234567890', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQGi6V--sKax2oA6-C4uq8Zr-3wVV1-R3DtZX34JIZBHddbclMcGYgAHm6JVEZqt_RJpvXaFmWi&usqp=CAc', 'Summary of Book 2', 'available', 3.8),
  ('Be You!', 3, '2023-03-05', 'Science Fiction', '9782345678901', 'https://m.media-amazon.com/images/I/61Om6ueoH2L._SL1200_.jpg', 'Summary of Book 3', 'rentedout', 4.5);
  ('Java : a beginners guide', 1, '2017-10-15', 'Java (Computer program language)', '9781260463552', 'https://ds.sasklibraries.ca/cover/l/3149982', 'Summary of Book 1', 'available', 4.2),
  ('Learning Python Mark Lutz', 2, '2021-07-20', 'Python (Computer program language)', '0596513984', 'https://ds.sasklibraries.ca/cover/l/3144069', 'Describes the features of the Python 2.5 programming language, covering such topics as types and operations, statements and syntax, functions, modules, classes and OOP, and exceptions and tools.', 'available', 3.8),
  ('50 years of silence / Jan Ruff-OHerne', 3, '2023-03-05', 'Science Fiction', '1875892001', 'https://ds.sasklibraries.ca/cover/l/425874', 'Summary of Book 3', 'available', 4.5),
  ('Core Java. Volume 2, Advanced features / Cay S. Horstmann.', 3, '2023-03-05', 'Java (Computer program language)', '9780135166314', 'https://example.com/cover3.jpg', '"Core Java" is the leading no-nonsense tutorial and reference for experienced programmers who want to write robust Java code for real-world applications. Now, "Core Java, volume II, advanced features, eleventh edition" has been revised to reflect Java II, with complete coverage of advanced UI and enterprise programming, networking, security, and Java\''s powerful new module system.', 'available', 4.5), 
  ('Title 3', 3, '2023-03-05', 'Science Fiction', '9782345678901', 'https://example.com/cover3.jpg', 'Summary of Book 3', 'available', 4.5), 
   ('Learn Java in One Day and Learn It Well', 3, '2023-03-05', 'Science', '9782345678', 'https://m.media-amazon.com/images/I/61KFmcmEK1L._SY466_.jpg', 'Complex concepts are broken down into simple steps to ensure that you can easily master the Java language even if you have never coded before.', 'available', 4.5);
  ('Return to Robinswood', 4, '2023-03-05', 'Fiction', '1875892001', 'https://m.media-amazon.com/images/I/71mBUq0uCQL._SY466_.jpg', 'Years of neglect and abandonment have left the family seat of the Keneficks almost derelict, but the new Lord Kenefick and his charming young wife Kate, are determined to breathe life into the old house once more The war is over and they have survived, so now they must set about making a bright future for themselves and their family. But the shadows of the past are ever lurking, and there are many who are not willing to see the new Lady Kenefick as anything more than the housekeeper’s daughter. Kate’s family, the Murphys, find themselves once more, inextricably entwined with both the Keneficks and Robinswood, but this time everything is different. Or at least they hope it is. The legacy of the war cannot be erased, and the events of those fateful years will not be forgotten. Can Robinswood provide a haven for those who need it, or are the scars of the past too deep?', 'available', 4.5),
  ('Core Java. Volume 2', 3, '2023-03-05', 'Java (Computer program language)', '9780135166314', 'https://m.media-amazon.com/images/I/41NIcBcopKL._SY445_SX342_.jpg', '"Core Java" is the leading no-nonsense tutorial and reference for experienced programmers who want to write robust Java code for real-world applications. Now, "Core Java, volume II, advanced features, eleventh edition" has been revised to reflect Java II, with complete coverage of advanced UI and enterprise programming, networking, security, and Java\''s powerful new module system.', 'available', 4.5), 
  ('What Once Was True', 4, '2022-03-05', 'Fiction', '95678901', 'https://m.media-amazon.com/images/I/51EXsTTKYCL._SY445_SX342_.jpg', 'The once grand house is home to two very different families.Despite delusions of grandeur, Lord and Lady Kenefick and their adult children, live a life of decayed opulence as the money needed to keep such a large house and grounds ever dwindles. Meanwhile, the Murphy family, Dermot, Isabella and their three almost grown up girls, live and work on the estate and do their best to keep everything running smoothly. Social structure is vital. Everyone knows their place, but as war looms, both families find themselves drawn into the conflict and begin questioning everything that once was true. From the leafy grounds of an Irish stately home, to the bombed out streets of London in the Blitz, allow yourself to be swept away once more in Jean Grainger’s latest bestselling historical saga.', 'available', 5), 
  ('Trials and Tribulations', 4, '2023-03-05', 'Fiction', '978234561', 'https://m.media-amazon.com/images/I/71JOcIIn2fL._SY466_.jpg', 'Three sisters, the three men that love them, and a house that could consume them all. Assuming their roles as the new Lord and Lady Kenefick and returning to Robinswood with the plan to drag it back from the brink of dereliction, is taking its toll on Kate and Sam. With a young family to raise, a very limited budget and only Kate’s parents to help, the task seems insurmountable. Kate’s eldest sister Eve and her husband Bartley have found happiness in each other after some dark years, but when a face from the past appears, it seems that everything they have worked so hard to create is threatened. Aisling, the middle sister, is being evasive and the family suspect something is very wrong. On the face of it, she has it all, a lovely husband, a comfortable house and a supportive family, but she is in deep trouble, and nobody can even guess at the real reason why. Meanwhile Lady Lillian, Sam’s sister, is useless and arrogant, refusing to accept that things have changed and that her title is not going to get her what she wants, least of all from her husband Beau. In the midst of it all Dermot and Isabella Murphy try their best to maintain a life and a home for their family, but the trials and tribulations of life at Robinswood might just tear them all apart. .', 'available', 4.8), 
  ('Rivers of Wrath', 3, '2023-03-05', 'Science Fiction', '9782345444901', 'https://m.media-amazon.com/images/I/51jJrcVxi4L._SY445_SX342_.jpg', 'When Cullen’s Celtic Cabaret rolls into a sleepy Irish seaside town, their eccentric and theatrical presence stirs up a flurry of excitement—the public clamouring to buy tickets for the greatest show in Ireland.Set against the backdrop of a relentless war for Ireland’s freedom, the stakes are higher than ever for Peter Cullen and his troupe as they try to stay out of the conflict. But as they soon discover, that’s a luxury nobody can afford. As well as fighting the forces of occupation, some people are using this time of chaos to settle old scores, and it seems the cabaret has gathered some sinister enemies. With danger lurking around every corner, Peter must fight to protect all he’s worked so hard to build.Rivers of Wrath is the third book in the Cullen’s Celtic Cabaret Series.', 'available', 4.7), 
  ('The Existential Worries of Mags Munroe', 4, '2023-03-05', 'Fiction', '978238901', 'https://m.media-amazon.com/images/I/81MXFndVZrL._SY466_.jpg', 'My twelve-year-old daughter frequently moans that Ballycarrick is the most boring town in Ireland. Nothing ever happens here.She’s right.And as the local police sergeant, this is something I’m delighted about.I’ve enough to worry about - the polar ice-caps, the evil monster that’s shrinking my trousers, not to mention the hot flushes - without having to be like one of those gritty Netflix cops, chasing criminals down alleyways and busting drug deals.', 'available', 4.5), 
  ('The Star and the Shamrock', 4, '2023-03-05', 'Fiction', '97823458901', 'https://m.media-amazon.com/images/I/615QyOCnCNL._SY466_.jpg', 'When her husband doesn’t come home one day, Ariella realises that the only way she can ensure her Jewish children’s safety is to avail of the Kindertransport, but can she bear to let them go? A thousand miles away, Elizabeth Klein has closed herself off from the world. Losing her husband on the last day of the Great War, and her child months later, she cannot, will not, love again. It hurts too much. But she is all Liesl and Erich Bannon have.', 'available', 4.9), 
  ('The Harp and the Rose', 4, '2023-03-05', 'Fiction', '9782348901', 'https://m.media-amazon.com/images/I/91QMOKkka+S._SY466_.jpg', 'For twenty-year-old Harp Devereaux, life should be idyllic. At university, she feels for the first time in her life that she belongs, her mother Rose is running the Cliff House as a successful business, and her childhood sweetheart JohnJoe is by her side, but the storm clouds of war grow ever darker. For eight hundred years Ireland has made numerous bids for her freedom but now, at last, liberation from British rule is tantalisingly close, if the men and women of the revolution can just hold on. Harp, her family, and her friends find themselves in the thick of the fight, but the Crown Forces are not the only enemy. A sinister force from the past is lurking and will stop at nothing to exact his revenge.', 'available', 4.9),
  ('Learn Java in One Day and Learn It Well', 3, '2023-03-05', 'Science', '9782345678', 'https://m.media-amazon.com/images/I/61KFmcmEK1L._SY466_.jpg', 'Complex concepts are broken down into simple steps to ensure that you can easily master the Java language even if you have never coded before.', 'available', 4.5);

