INSERT INTO books (title, author_id, publication_date, genre, isbn, cover_image_url, summary, rating) VALUES
  ('Java : a beginners guide', 1, '2017-10-15', 'Computer program language', '978126330463552', 'https://ds.sasklibraries.ca/cover/l/3149982', 'Summary of Book 1', 4.2),
  ('The Gift of Culture', 5, '2021-12-19', 'Workplace Behavior', '978126046323552', 'https://m.media-amazon.com/images/I/617TpeOLd5L._SY466_.jpg', 'Leaders make profound contributions to the world by creating environments where people thrive so they can be the best that they can be. This can only happen in businesses with a culture of excellence. Over time, the ripple effect of culture-conscious leadership extends beyond the walls of the workplace culture and into the lives, families, and communities of all the employees, customers, and vendors. Despite the measurable returns on culture, however, many leaders don’t necessarily know how to create a great culture. Until now. Culture is our business.', 4.2),
  ('Small Habits Revolution', 1, '2017-10-15', 'Health and Stress Management', '904652', 'https://ds.sasklibraries.ca/cover/l/3149982', 'Do you find yourself trying to adopt good habits only to abandon them down the road? Are you frustrated because you seem unable to develop them in the first place? You/''re not alone! Most people fail when they try to incorporate new habits into their day. It/''s not for lack of good intentions. Like you and I, they want to lead more rewarding lives. They have plenty of motivation. They also possess willpower. But neither are enough. Predictably, their new habits fail to take root, and are eventually abandoned and forgotten. Can you relate to this problem? If so, there/''s a simple solution: starting small. This effective, time-tested method is described in detail in Small Habits Revolution: 10 Steps To Transforming Your Life Through The Power Of Mini Habits! ', 4.2),
  ('The Business Case for AI', 1, '2018-10-15', 'Computer program language', '97860463552', 'https://m.media-amazon.com/images/I/61HAWA+cXQL._SY466_.jpg', 'AI is much more than a sexy marketing gimmick. At its core, it’s a powerful business tool that can make operations and decision-making more efficient, employees more productive, and customers delighted. Unfortunately, leaders who want to take advantage of artificial intelligence often don’t know where to start. The process can feel overwhelming—from analyzing existing processes and software systems and choosing where to apply AI automation, to preparing every tier of the organization for the transition. In this practical guide for business leaders, Kavita Ganesan takes the mystery out of implementing AI, showing you how to launch AI initiatives that get results. With real-world AI examples to spark your own ideas, you’ll learn how to identify high-impact AI opportunities, prepare for AI transitions, and measure your AI performance.', 4.2),
  ('Learning Python Mark Lutz', 2, '2021-07-20', 'Computer program language', '0596513984', 'https://ds.sasklibraries.ca/cover/l/3144069', 'Describes the features of the Python 2.5 programming language, covering such topics as types and operations, statements and syntax, functions, modules, classes and OOP, and exceptions and tools.', 3.8),
  ('50 years of silence / Jan Ruff-OHerne', 3, '2023-03-05', 'Science Fiction', '1875892001', 'https://ds.sasklibraries.ca/cover/l/425874', 'Summary of Book 3', 4.5),
  ('Core Java. Volume 2, Advanced features / Cay S. Horstmann.', 3, '2023-03-05', 'Java (Computer program language)', '9780135166314', 'https://ds.sasklibraries.ca/cover/l/2695370', '"Core Java" is the leading no-nonsense tutorial and reference for experienced programmers who want to write robust Java code for real-world applications. Now, "Core Java, volume II, advanced features, eleventh edition" has been revised to reflect Java II, with complete coverage of advanced UI and enterprise programming, networking, security, and Java\''s powerful new module system.', 4.5), 
  ('Java by comparison : become a Java craftsman in 70 examples', 3, '2023-03-05', 'Java (Computer program language)', '97801366314', 'https://ds.sasklibraries.ca/cover/l/2593523', '"Summary', 4.5),
  ('The power of Java', 3, '2023-03-05', 'Computer program language', '978013314', 'https://ds.sasklibraries.ca/cover/l/2520749', '"Summary', 4.5), 
  ('Learning Java : an introduction to real-world programming with Java', 3, '2023-03-05', 'Science Fiction', '9782345678901', 'https://ds.sasklibraries.ca/cover/l/3010969', 'If you/''re new to Java or new to programming, this best-selling book will guide you through the language features and APIs of Java 11. With fun, compelling, and realistic examples, authors Marc Loy, Patrick Niemeyer, and Daniel Leuck introduce you to Java fundamentals including its class libraries, programming techniques, and idioms with an eye toward building real applications. You/''ll learn powerful new ways to manage resources and exceptions in your applications, along with core language features included in recent Java versions. Develop with Java, using the compiler, interpreter, and other tools. Explore Java/''s built-in thread facilities and concurrency package. Learn text processing and the powerful regular expressions API. Write advanced networked or web-based applications and services.', 4.5), 
  ('Book', 5, '2017-10-15', 'Fiction', '97', 'https', 'Summary', 4.2),
   ('Learn Java in One Day and Learn It Well', 3, '2023-03-05', 'Science', '9782345678', 'https://m.media-amazon.com/images/I/61KFmcmEK1L._SY466_.jpg', 'Complex concepts are broken down into simple steps to ensure that you can easily master the Java language even if you have never coded before.', 4.5);
